spring.application.name=lab1_inf
spring.data.jpa.repositories.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name = org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=oFCD.9205
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
jwt.secret = GzhRWSagWqLJWMRLyABo8JCcwdmA/Rs46okSn0GBl6c=GzhRWSagWqLJWMRLyABo8JCcwdmA/Rs46okSn0GBl6c=
jwt.lifetime = 30m